### ISSUE TITLE
Buen trabajo!

### ISSUE THREAD

**Issue by danmt** [ElieGonzalez/AngularApp#1]
Tu proyecto está casi listo. Al correrlo con `nx serve` da un error de process, el ejemplo de polyfills tiene un error. Para arreglarlo, reemplaza el contenido de [los polyfills](https://github.com/ElieGonzalez/AngularApp/blob/main/src/polyfills.ts) con este codigo:

```typescript
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Buffer } from "buffer";

(window as any).global = window;
(window as any).global.Buffer = Buffer;
(window as any).process = { env: { }};  
```

**Comment by ElieGonzalez** [comment]
Gracias por la correción, ya tenia una idea del error de process porque de hecho lo habia mencionado en el discord pero esperaba por las correcciones de ustedes.
